<?php

namespace ContainerNiL2v1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGkXrioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pGkXrio' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pGkXrio'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postManager' => ['privates', 'Domain\\Post\\PostManager', 'getPostManagerService', true],
        ], [
            'postManager' => 'Domain\\Post\\PostManager',
        ]);
    }
}
