<?php

namespace ContainerNiL2v1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddPostCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AddPostCommand' shared autowired service.
     *
     * @return \App\Command\AddPostCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/App/Command/AddPostCommand.php';

        $container->privates['App\\Command\\AddPostCommand'] = $instance = new \App\Command\AddPostCommand(($container->privates['Domain\\Post\\PostManager'] ?? $container->load('getPostManagerService')));

        $instance->setName('app:add-post');
        $instance->setDescription('Run app:add-post');

        return $instance;
    }
}
