<?php

namespace ContainerNiL2v1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateRandomPostCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateRandomPostCommand' shared autowired service.
     *
     * @return \App\Command\GenerateRandomPostCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/App/Command/GenerateRandomPostCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/joshtronic/php-loremipsum/src/LoremIpsum.php';

        $container->privates['App\\Command\\GenerateRandomPostCommand'] = $instance = new \App\Command\GenerateRandomPostCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), new \joshtronic\LoremIpsum());

        $instance->setName('app:generate-random-post');
        $instance->setDescription('Run app:generate-random-post');

        return $instance;
    }
}
