<?php

namespace ContainerNiL2v1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Domain\Post\PostManager' shared autowired service.
     *
     * @return \Domain\Post\PostManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Post/PostManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['Domain\\Post\\PostManager'])) {
            return $container->privates['Domain\\Post\\PostManager'];
        }

        return $container->privates['Domain\\Post\\PostManager'] = new \Domain\Post\PostManager($a);
    }
}
